#!/usr/bin/env bash
# script that groups visitors by IP and HTTP status code,
# and displays this data.

LOG_FILE="access.log"

awk '{
  ip = $1
  httpCode = $9
  key = ip " " httpCode
  occurrences[key]++
}
END {
  for (k in occurrences) {
    print occurrences[k], k
  }
}' "${LOG_FILE}" | sort -rn

