#!/usr/bin/env bash
# this script print "Best School" ten times and print "Hi" in 9th iteration

a=0

while [ $a -lt 10 ]; do
      echo "Best School"
      if [ $a -eq 8 ]; then
	  echo "Hi"
      fi
      a=$((a+1))
done

