#!/usr/bin/env bash
# this script loop from 1 up to 10 and print "bad luck" in 4th ,
# "good luck" in 8th iter, and "Best School" for the rest

a=1

while [ $a -le 10 ]; do
      if [ $a -eq 4 ]; then
      	 echo "bad luck"
      elif [ $a -eq 8 ]; then
	 echo "good luck"
      else
	 echo "Best School"
      fi
      a=$((a+1))
done

