#!/usr/bin/env bash
# the string "bad luck from China" in the 4th loop
# the string "bad luck from Japan" in the 9th loop
# the string "bad luck from Italy" in the 17th loop

a=1

while [ $a -le 20 ]; do
    echo "$a"
    case "$a" in
	4)
	    echo "bad luck from China" ;;
	9)
	    echo "bad luck from Japan" ;;
	17)
	    echo "bad luck from Italy" ;;
    esac
    a=$((a+1))
done

